/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#f54e00',
        'primary-active': '#d04200',
        'primary-hover': '#d04200',
        'primary-light': '#fafaf7',
        ink: '#26251e',
        body: '#5a5852',
        'body-strong': '#26251e',
        muted: '#807d72',
        'muted-soft': '#a09c92',
        hairline: '#e6e5e0',
        'hairline-soft': '#efeee8',
        'hairline-strong': '#cfcdc4',
        canvas: '#f7f7f4',
        'canvas-soft': '#fafaf7',
        'surface-card': '#ffffff',
        'surface-strong': '#e6e5e0',
        success: '#1f8a65',
        error: '#cf2d56',
        'timeline-thinking': '#dfa88f',
        'timeline-grep': '#9fc9a2',
        'timeline-read': '#9fbbe0',
        'timeline-edit': '#c0a8dd',
        'timeline-done': '#c08532',
        slate: {
          50: '#f7f7f4',
          100: '#efeee8',
          150: '#e6e5e0',
          200: '#e6e5e0',
          300: '#cfcdc4',
          400: '#a09c92',
          450: '#807d72',
          500: '#807d72',
          600: '#5a5852',
          700: '#26251e',
          800: '#26251e',
          850: '#26251e',
          900: '#26251e',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        'display-mega': ['72px', { lineHeight: '1.1', letterSpacing: '-2.16px', fontWeight: '400' }],
        'display-lg': ['36px', { lineHeight: '1.2', letterSpacing: '-0.72px', fontWeight: '400' }],
        'display-md': ['26px', { lineHeight: '1.25', letterSpacing: '-0.325px', fontWeight: '400' }],
        'display-sm': ['22px', { lineHeight: '1.3', letterSpacing: '-0.11px', fontWeight: '400' }],
      },
      borderRadius: {
        md: '8px',
        lg: '12px',
        xl: '16px',
      },
      maxWidth: {
        content: '1200px',
      },
      spacing: {
        section: '80px',
      },
      boxShadow: {
        none: 'none',
        premium: 'none',
        card: 'none',
        dropdown: 'none',
      },
    },
  },
  plugins: [],
}
